id: A885A5A88
title: A Sukhāvatī Prayer and Aspiration
type: translation
pechas:
- IDCF0448D
- I5FFC6151
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:46:04.961563
  last_modified_at: 2023-01-04 11:46:04.961575
  collections:
  - Dudjom Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IDCF0448D/B974: 0DAD
  I5FFC6151/783D: 0DAD
